// This file is generated by Velite

import type __vc from '../velite.config.ts'

type Collections = typeof __vc.collections

export type posts = Collections['posts']['schema']['_output']
export declare const posts: posts[]

export type lessons = Collections['lessons']['schema']['_output']
export declare const lessons: lessons[]

export type domains = Collections['domains']['schema']['_output']
export declare const domains: domains[]

export type skills = Collections['skills']['schema']['_output']
export declare const skills: skills[]

export type courses = Collections['courses']['schema']['_output']
export declare const courses: courses[]

export type modules = Collections['modules']['schema']['_output']
export declare const modules: modules[]

export type courseLessons = Collections['courseLessons']['schema']['_output']
export declare const courseLessons: courseLessons[]

export type learningPaths = Collections['learningPaths']['schema']['_output']
export declare const learningPaths: learningPaths[]

export type badges = Collections['badges']['schema']['_output']
export declare const badges: badges[]

export type glossary = Collections['glossary']['schema']['_output']
export declare const glossary: glossary[]
