// This file is generated by Velite

export { default as posts } from './posts.json' with { type: 'json' }
export { default as lessons } from './lessons.json' with { type: 'json' }
export { default as domains } from './domains.json' with { type: 'json' }
export { default as skills } from './skills.json' with { type: 'json' }
export { default as courses } from './courses.json' with { type: 'json' }
export { default as modules } from './modules.json' with { type: 'json' }
export { default as courseLessons } from './courseLessons.json' with { type: 'json' }
export { default as learningPaths } from './learningPaths.json' with { type: 'json' }
export { default as badges } from './badges.json' with { type: 'json' }
export { default as glossary } from './glossary.json' with { type: 'json' }